### PR TITLE
Create podmanInstaller.yml

### PR DESCRIPTION
**Pull request by MercMonster**
Here is the install for podman on Ansible

### CODE REVIEW

**Review by jonespaul327 — APPROVED** [review]

**Review by tmburks42 — APPROVED** [review]

**Comment by RothAndrew** [comment]
Did you mean to close this? Shouldn't it be merged?

**Comment by MercMonster** [comment]
yes i meant to close this. Paul and myself got more code together that installs both zhyve and podman. Also it updates homebrew if needed.

**Comment by MercMonster** [comment]
The pull request attached to issue number 18 is also supposed to be attached here but i can not see a way to connect multiple issues.

**Comment by MercMonster** [comment]
i can merge it though if you would prefer me to do that.

**Comment by RothAndrew** [comment]
Nope just making sure it wasn't an accident

**Pull request closed without merging**
